import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'ar' | 'de' | 'fr' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const languages: { code: Language; name: string; nativeName: string; flag: string }[] = [
  { code: 'en', name: 'English', nativeName: 'English', flag: '🇬🇧' },
  { code: 'ar', name: 'Arabic', nativeName: 'العربية', flag: '🇪🇬' },
  { code: 'de', name: 'German', nativeName: 'Deutsch', flag: '🇩🇪' },
  { code: 'fr', name: 'French', nativeName: 'Français', flag: '🇫🇷' },
  { code: 'es', name: 'Spanish', nativeName: 'Español', flag: '🇪🇸' },
];

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'en';
  });

  const isRTL = language === 'ar';

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.dir = isRTL ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language, isRTL]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    const keys = key.split('.');
    let value: any = translations[language];
    
    for (const k of keys) {
      value = value?.[k];
    }
    
    return value || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

const translations: Record<Language, Record<string, any>> = {
  en: {
    nav: {
      home: 'Home',
      cruises: 'Our Cruises',
      accommodations: 'Accommodations',
      gallery: 'Gallery',
      contact: 'Contact',
      bookNow: 'Book Now',
    },
    hero: {
      tagline: 'Luxury Nile Cruise Experience',
      title: 'Prince',
      titleHighlight: 'Omar',
      description: 'Embark on a journey through ancient Egypt aboard our magnificent 5-star cruise. Discover timeless temples and breathtaking landscapes in unparalleled luxury.',
      bookJourney: 'Book Your Journey',
      exploreCruises: 'Explore Cruises',
      luxuryRooms: 'Luxury Rooms',
      royalSuites: 'Royal Suites',
      rating: 'Rating',
    },
    cruises: {
      tagline: 'Our Journeys',
      title: 'Nile Cruise Itineraries',
      description: 'Choose from our carefully curated cruise experiences, each offering unique perspectives of Egypt\'s ancient wonders and natural beauty.',
      luxorToAswan: 'Luxor to Aswan',
      aswanToLuxor: 'Aswan to Luxor',
      nights: 'Nights',
      days: 'Days',
      everyMonday: 'Every Monday',
      everyFriday: 'Every Friday',
      highlights: 'Highlights',
      inquireNow: 'Inquire Now',
      bookThisCruise: 'Book This Cruise',
      luxorDesc: 'Begin your journey in Luxor, the world\'s greatest open-air museum, and sail south to the enchanting city of Aswan.',
      aswanDesc: 'Start in Aswan, navigate through the Nile\'s gentle waters, and conclude in legendary Luxor.',
      itinerary: 'Day by Day Itinerary',
    },
    included: {
      tagline: 'Amenities',
      title: 'What\'s Included',
      description: 'Every detail has been thoughtfully considered to ensure your journey is nothing short of extraordinary.',
      fullBoard: 'Full Board Meals',
      fullBoardDesc: 'Exquisite breakfast, lunch, and dinner with international and local cuisine',
      welcomeDrink: 'Welcome Drink',
      welcomeDrinkDesc: 'Refreshing welcome cocktail upon embarkation',
      teaCoffee: 'Tea & Coffee',
      teaCoffeeDesc: 'Complimentary tea and coffee available throughout the day',
      guidedTours: 'Guided Tours',
      guidedToursDesc: 'Professional Egyptologist guides for all temple visits',
      pool: 'Swimming Pool',
      poolDesc: 'Sundeck pool with panoramic Nile views',
      entertainment: 'Entertainment',
      entertainmentDesc: 'Nightly entertainment including Nubian shows and Galabeya parties',
      wifi: 'Wi-Fi Access',
      wifiDesc: 'Stay connected with onboard internet service',
      housekeeping: 'Daily Housekeeping',
      housekeepingDesc: 'Premium housekeeping service twice daily',
      personalService: 'Personal Service',
      personalServiceDesc: 'Attentive staff dedicated to your comfort',
      safety: 'Safety & Security',
      safetyDesc: '24/7 security and safety protocols',
    },
    accommodations: {
      tagline: 'Accommodations',
      title: 'Luxury Cabins & Suites',
      description: 'Each cabin aboard Prince Omar has been designed with your comfort in mind, featuring elegant décor and modern amenities.',
      standardRoom: 'Standard Cabin',
      royalSuite: 'Royal Suite',
      roomsAvailable: 'Rooms Available',
      suitesAvailable: 'Suites Available',
      viewAll: 'View All Accommodations',
      premiumExperience: 'Premium Experience',
      inquireRoom: 'Inquire About This Room',
    },
    gallery: {
      tagline: 'Gallery',
      title: 'Experience the Beauty',
      description: 'Take a glimpse into the world of Prince Omar Nile Cruise through our gallery.',
      viewFull: 'View Full Gallery',
      all: 'All',
      exterior: 'Exterior',
      interior: 'Interior',
      cabins: 'Cabins',
      dining: 'Dining',
      deck: 'Deck',
    },
    contact: {
      tagline: 'Get in Touch',
      title: 'Contact Us',
      description: 'Ready to embark on your Nile adventure? We\'re here to help you plan the perfect cruise experience.',
      readyToSail: 'Ready to Sail?',
      beginJourney: 'Begin Your Nile Journey Today',
      ctaDescription: 'Contact us to book your unforgettable cruise experience or to learn more about our exclusive packages and special offers.',
      whatsappUs: 'WhatsApp Us',
      emailUs: 'Email Us',
      loveToHear: 'We\'d Love to Hear From You',
      helpText: 'Whether you have questions about our cruises, need help with booking, or want to learn more about special packages, our team is ready to assist you.',
      whatsapp: 'WhatsApp',
      fastestResponse: 'Fastest response • Click to chat',
      phone: 'Phone',
      available7Days: 'Available 7 days a week',
      email: 'Email',
      respondWithin: 'We respond within 24 hours',
      location: 'Location',
      website: 'Website',
      sendMessage: 'Send Us a Message',
      yourName: 'Your Name',
      enterName: 'Enter your name',
      emailAddress: 'Email Address',
      phoneNumber: 'Phone Number',
      yourMessage: 'Your Message',
      tellUs: 'Tell us about your travel plans...',
      sendViaWhatsapp: 'Send via WhatsApp',
      messageSentVia: 'Your message will be sent via WhatsApp for fastest response',
      nileRiver: 'Nile River',
      luxorAswan: 'Luxor & Aswan, Egypt',
    },
    footer: {
      description: 'Experience the timeless beauty of the Nile aboard our luxury cruise. Where ancient wonders meet modern comfort.',
      quickLinks: 'Quick Links',
      ourCruises: 'Our Cruises',
      contactUs: 'Contact Us',
      allRights: 'All rights reserved.',
    },
    common: {
      respond24h: 'We respond within 24 hours • Available 7 days a week',
    },
  },
  ar: {
    nav: {
      home: 'الرئيسية',
      cruises: 'رحلاتنا',
      accommodations: 'الإقامة',
      gallery: 'معرض الصور',
      contact: 'اتصل بنا',
      bookNow: 'احجز الآن',
    },
    hero: {
      tagline: 'تجربة رحلة نيلية فاخرة',
      title: 'الأمير',
      titleHighlight: 'عمر',
      description: 'انطلق في رحلة عبر مصر القديمة على متن رحلتنا البحرية ذات الخمس نجوم. اكتشف المعابد الخالدة والمناظر الطبيعية الخلابة في رفاهية لا مثيل لها.',
      bookJourney: 'احجز رحلتك',
      exploreCruises: 'استكشف الرحلات',
      luxuryRooms: 'غرفة فاخرة',
      royalSuites: 'جناح ملكي',
      rating: 'التقييم',
    },
    cruises: {
      tagline: 'رحلاتنا',
      title: 'برامج الرحلات النيلية',
      description: 'اختر من بين تجارب الرحلات البحرية المنتقاة بعناية، كل منها يقدم منظورًا فريدًا لعجائب مصر القديمة وجمالها الطبيعي.',
      luxorToAswan: 'الأقصر إلى أسوان',
      aswanToLuxor: 'أسوان إلى الأقصر',
      nights: 'ليالٍ',
      days: 'أيام',
      everyMonday: 'كل يوم اثنين',
      everyFriday: 'كل يوم جمعة',
      highlights: 'أبرز المعالم',
      inquireNow: 'استفسر الآن',
      bookThisCruise: 'احجز هذه الرحلة',
      luxorDesc: 'ابدأ رحلتك في الأقصر، أعظم متحف مفتوح في العالم، وأبحر جنوبًا إلى مدينة أسوان الساحرة.',
      aswanDesc: 'ابدأ في أسوان، وانطلق عبر مياه النيل الهادئة، واختتم في الأقصر الأسطورية.',
      itinerary: 'البرنامج اليومي',
    },
    included: {
      tagline: 'المرافق',
      title: 'ما يشمله السعر',
      description: 'تم التفكير بعناية في كل التفاصيل لضمان أن تكون رحلتك استثنائية.',
      fullBoard: 'إقامة كاملة',
      fullBoardDesc: 'إفطار وغداء وعشاء فاخر مع مأكولات عالمية ومحلية',
      welcomeDrink: 'مشروب ترحيبي',
      welcomeDrinkDesc: 'كوكتيل ترحيبي منعش عند الصعود',
      teaCoffee: 'شاي وقهوة',
      teaCoffeeDesc: 'شاي وقهوة مجانية متاحة طوال اليوم',
      guidedTours: 'جولات إرشادية',
      guidedToursDesc: 'مرشدون مصريون محترفون لجميع زيارات المعابد',
      pool: 'حمام سباحة',
      poolDesc: 'حمام سباحة على السطح مع إطلالات بانورامية على النيل',
      entertainment: 'ترفيه',
      entertainmentDesc: 'سهرات ترفيهية تشمل عروض نوبية وحفلات الجلابية',
      wifi: 'واي فاي',
      wifiDesc: 'ابقَ متصلاً بخدمة الإنترنت على متن السفينة',
      housekeeping: 'تنظيف يومي',
      housekeepingDesc: 'خدمة تنظيف فاخرة مرتين يوميًا',
      personalService: 'خدمة شخصية',
      personalServiceDesc: 'طاقم عمل مهتم مخصص لراحتك',
      safety: 'الأمن والسلامة',
      safetyDesc: 'بروتوكولات أمن وسلامة على مدار الساعة',
    },
    accommodations: {
      tagline: 'الإقامة',
      title: 'كبائن وأجنحة فاخرة',
      description: 'تم تصميم كل كابينة على متن الأمير عمر مع مراعاة راحتك، وتتميز بديكور أنيق ووسائل راحة حديثة.',
      standardRoom: 'كابينة قياسية',
      royalSuite: 'جناح ملكي',
      roomsAvailable: 'غرفة متاحة',
      suitesAvailable: 'جناح متاح',
      viewAll: 'عرض جميع الإقامات',
      premiumExperience: 'تجربة مميزة',
      inquireRoom: 'استفسر عن هذه الغرفة',
    },
    gallery: {
      tagline: 'معرض الصور',
      title: 'استمتع بالجمال',
      description: 'ألقِ نظرة على عالم رحلة الأمير عمر النيلية من خلال معرض الصور.',
      viewFull: 'عرض المعرض الكامل',
      all: 'الكل',
      exterior: 'الخارج',
      interior: 'الداخل',
      cabins: 'الكبائن',
      dining: 'المطعم',
      deck: 'السطح',
    },
    contact: {
      tagline: 'تواصل معنا',
      title: 'اتصل بنا',
      description: 'هل أنت مستعد للانطلاق في مغامرتك النيلية؟ نحن هنا لمساعدتك في التخطيط لتجربة الرحلة المثالية.',
      readyToSail: 'مستعد للإبحار؟',
      beginJourney: 'ابدأ رحلتك النيلية اليوم',
      ctaDescription: 'اتصل بنا لحجز تجربة رحلتك التي لا تُنسى أو لمعرفة المزيد عن باقاتنا الحصرية والعروض الخاصة.',
      whatsappUs: 'راسلنا واتساب',
      emailUs: 'راسلنا بريديًا',
      loveToHear: 'يسعدنا سماع رأيك',
      helpText: 'سواء كانت لديك أسئلة حول رحلاتنا، أو تحتاج مساعدة في الحجز، أو تريد معرفة المزيد عن الباقات الخاصة، فريقنا جاهز لمساعدتك.',
      whatsapp: 'واتساب',
      fastestResponse: 'أسرع استجابة • انقر للدردشة',
      phone: 'الهاتف',
      available7Days: 'متاح 7 أيام في الأسبوع',
      email: 'البريد الإلكتروني',
      respondWithin: 'نرد خلال 24 ساعة',
      location: 'الموقع',
      website: 'الموقع الإلكتروني',
      sendMessage: 'أرسل لنا رسالة',
      yourName: 'اسمك',
      enterName: 'أدخل اسمك',
      emailAddress: 'البريد الإلكتروني',
      phoneNumber: 'رقم الهاتف',
      yourMessage: 'رسالتك',
      tellUs: 'أخبرنا عن خطط سفرك...',
      sendViaWhatsapp: 'إرسال عبر واتساب',
      messageSentVia: 'سيتم إرسال رسالتك عبر واتساب للحصول على أسرع استجابة',
      nileRiver: 'نهر النيل',
      luxorAswan: 'الأقصر وأسوان، مصر',
    },
    footer: {
      description: 'استمتع بجمال النيل الخالد على متن رحلتنا الفاخرة. حيث تلتقي العجائب القديمة بالراحة الحديثة.',
      quickLinks: 'روابط سريعة',
      ourCruises: 'رحلاتنا',
      contactUs: 'اتصل بنا',
      allRights: 'جميع الحقوق محفوظة.',
    },
    common: {
      respond24h: 'نرد خلال 24 ساعة • متاح 7 أيام في الأسبوع',
    },
  },
  de: {
    nav: {
      home: 'Startseite',
      cruises: 'Unsere Kreuzfahrten',
      accommodations: 'Unterkünfte',
      gallery: 'Galerie',
      contact: 'Kontakt',
      bookNow: 'Jetzt Buchen',
    },
    hero: {
      tagline: 'Luxuriöses Nil-Kreuzfahrt-Erlebnis',
      title: 'Prinz',
      titleHighlight: 'Omar',
      description: 'Begeben Sie sich auf eine Reise durch das alte Ägypten an Bord unserer prächtigen 5-Sterne-Kreuzfahrt. Entdecken Sie zeitlose Tempel und atemberaubende Landschaften in beispiellosem Luxus.',
      bookJourney: 'Reise Buchen',
      exploreCruises: 'Kreuzfahrten Erkunden',
      luxuryRooms: 'Luxuszimmer',
      royalSuites: 'Königliche Suiten',
      rating: 'Bewertung',
    },
    cruises: {
      tagline: 'Unsere Reisen',
      title: 'Nil-Kreuzfahrt-Routen',
      description: 'Wählen Sie aus unseren sorgfältig kuratierten Kreuzfahrt-Erlebnissen, die jeweils einzigartige Perspektiven auf Ägyptens antike Wunder bieten.',
      luxorToAswan: 'Luxor nach Assuan',
      aswanToLuxor: 'Assuan nach Luxor',
      nights: 'Nächte',
      days: 'Tage',
      everyMonday: 'Jeden Montag',
      everyFriday: 'Jeden Freitag',
      highlights: 'Höhepunkte',
      inquireNow: 'Jetzt Anfragen',
      bookThisCruise: 'Diese Kreuzfahrt Buchen',
      luxorDesc: 'Beginnen Sie Ihre Reise in Luxor, dem größten Freilichtmuseum der Welt, und segeln Sie südlich zur bezaubernden Stadt Assuan.',
      aswanDesc: 'Starten Sie in Assuan, navigieren Sie durch die sanften Gewässer des Nils und enden Sie im legendären Luxor.',
      itinerary: 'Tagesablauf',
    },
    included: {
      tagline: 'Annehmlichkeiten',
      title: 'Was Inbegriffen Ist',
      description: 'Jedes Detail wurde sorgfältig durchdacht, um sicherzustellen, dass Ihre Reise außergewöhnlich wird.',
      fullBoard: 'Vollpension',
      fullBoardDesc: 'Exquisites Frühstück, Mittag- und Abendessen mit internationaler und lokaler Küche',
      welcomeDrink: 'Willkommensgetränk',
      welcomeDrinkDesc: 'Erfrischender Willkommenscocktail bei der Einschiffung',
      teaCoffee: 'Tee & Kaffee',
      teaCoffeeDesc: 'Kostenloser Tee und Kaffee den ganzen Tag',
      guidedTours: 'Geführte Touren',
      guidedToursDesc: 'Professionelle Ägyptologen-Führer für alle Tempelbesuche',
      pool: 'Schwimmbad',
      poolDesc: 'Sonnendeck-Pool mit Panoramablick auf den Nil',
      entertainment: 'Unterhaltung',
      entertainmentDesc: 'Abendliche Unterhaltung mit nubischen Shows und Galabeya-Partys',
      wifi: 'WLAN-Zugang',
      wifiDesc: 'Bleiben Sie mit dem Bordinternet verbunden',
      housekeeping: 'Tägliche Reinigung',
      housekeepingDesc: 'Premium-Reinigungsservice zweimal täglich',
      personalService: 'Persönlicher Service',
      personalServiceDesc: 'Aufmerksames Personal für Ihren Komfort',
      safety: 'Sicherheit',
      safetyDesc: '24/7 Sicherheitsprotokolle',
    },
    accommodations: {
      tagline: 'Unterkünfte',
      title: 'Luxuskabinen & Suiten',
      description: 'Jede Kabine an Bord des Prinz Omar wurde mit Ihrem Komfort im Sinn gestaltet.',
      standardRoom: 'Standardkabine',
      royalSuite: 'Königliche Suite',
      roomsAvailable: 'Zimmer Verfügbar',
      suitesAvailable: 'Suiten Verfügbar',
      viewAll: 'Alle Unterkünfte Ansehen',
      premiumExperience: 'Premium-Erlebnis',
      inquireRoom: 'Über Dieses Zimmer Anfragen',
    },
    gallery: {
      tagline: 'Galerie',
      title: 'Erleben Sie die Schönheit',
      description: 'Werfen Sie einen Blick in die Welt der Prinz Omar Nilkreuzfahrt.',
      viewFull: 'Vollständige Galerie',
      all: 'Alle',
      exterior: 'Außen',
      interior: 'Innen',
      cabins: 'Kabinen',
      dining: 'Restaurant',
      deck: 'Deck',
    },
    contact: {
      tagline: 'Kontakt',
      title: 'Kontaktieren Sie Uns',
      description: 'Bereit für Ihr Nil-Abenteuer? Wir helfen Ihnen bei der Planung Ihrer perfekten Kreuzfahrt.',
      readyToSail: 'Bereit zum Segeln?',
      beginJourney: 'Beginnen Sie Heute Ihre Nilreise',
      ctaDescription: 'Kontaktieren Sie uns, um Ihre unvergessliche Kreuzfahrt zu buchen.',
      whatsappUs: 'WhatsApp',
      emailUs: 'E-Mail',
      loveToHear: 'Wir Freuen Uns Von Ihnen Zu Hören',
      helpText: 'Ob Sie Fragen zu unseren Kreuzfahrten haben oder Hilfe bei der Buchung benötigen, unser Team ist bereit zu helfen.',
      whatsapp: 'WhatsApp',
      fastestResponse: 'Schnellste Antwort • Klicken zum Chatten',
      phone: 'Telefon',
      available7Days: '7 Tage die Woche erreichbar',
      email: 'E-Mail',
      respondWithin: 'Wir antworten innerhalb von 24 Stunden',
      location: 'Standort',
      website: 'Webseite',
      sendMessage: 'Nachricht Senden',
      yourName: 'Ihr Name',
      enterName: 'Namen eingeben',
      emailAddress: 'E-Mail-Adresse',
      phoneNumber: 'Telefonnummer',
      yourMessage: 'Ihre Nachricht',
      tellUs: 'Erzählen Sie uns von Ihren Reiseplänen...',
      sendViaWhatsapp: 'Via WhatsApp Senden',
      messageSentVia: 'Ihre Nachricht wird via WhatsApp gesendet',
      nileRiver: 'Nil',
      luxorAswan: 'Luxor & Assuan, Ägypten',
    },
    footer: {
      description: 'Erleben Sie die zeitlose Schönheit des Nils an Bord unserer Luxuskreuzfahrt.',
      quickLinks: 'Schnelllinks',
      ourCruises: 'Unsere Kreuzfahrten',
      contactUs: 'Kontakt',
      allRights: 'Alle Rechte vorbehalten.',
    },
    common: {
      respond24h: 'Wir antworten innerhalb von 24 Stunden • 7 Tage die Woche',
    },
  },
  fr: {
    nav: {
      home: 'Accueil',
      cruises: 'Nos Croisières',
      accommodations: 'Hébergements',
      gallery: 'Galerie',
      contact: 'Contact',
      bookNow: 'Réserver',
    },
    hero: {
      tagline: 'Expérience de Croisière de Luxe sur le Nil',
      title: 'Prince',
      titleHighlight: 'Omar',
      description: 'Embarquez pour un voyage à travers l\'Égypte ancienne à bord de notre magnifique croisière 5 étoiles. Découvrez des temples intemporels et des paysages à couper le souffle dans un luxe inégalé.',
      bookJourney: 'Réserver Votre Voyage',
      exploreCruises: 'Explorer les Croisières',
      luxuryRooms: 'Chambres de Luxe',
      royalSuites: 'Suites Royales',
      rating: 'Évaluation',
    },
    cruises: {
      tagline: 'Nos Voyages',
      title: 'Itinéraires de Croisière sur le Nil',
      description: 'Choisissez parmi nos expériences de croisière soigneusement sélectionnées, offrant des perspectives uniques sur les merveilles antiques de l\'Égypte.',
      luxorToAswan: 'Louxor à Assouan',
      aswanToLuxor: 'Assouan à Louxor',
      nights: 'Nuits',
      days: 'Jours',
      everyMonday: 'Chaque Lundi',
      everyFriday: 'Chaque Vendredi',
      highlights: 'Points Forts',
      inquireNow: 'Demander Maintenant',
      bookThisCruise: 'Réserver Cette Croisière',
      luxorDesc: 'Commencez votre voyage à Louxor, le plus grand musée à ciel ouvert du monde, et naviguez vers le sud jusqu\'à la ville enchanteresse d\'Assouan.',
      aswanDesc: 'Partez d\'Assouan, naviguez sur les eaux douces du Nil et terminez dans la légendaire Louxor.',
      itinerary: 'Itinéraire Jour par Jour',
    },
    included: {
      tagline: 'Commodités',
      title: 'Ce Qui Est Inclus',
      description: 'Chaque détail a été soigneusement pensé pour que votre voyage soit extraordinaire.',
      fullBoard: 'Pension Complète',
      fullBoardDesc: 'Petit-déjeuner, déjeuner et dîner exquis avec cuisine internationale et locale',
      welcomeDrink: 'Boisson de Bienvenue',
      welcomeDrinkDesc: 'Cocktail de bienvenue rafraîchissant à l\'embarquement',
      teaCoffee: 'Thé & Café',
      teaCoffeeDesc: 'Thé et café gratuits disponibles toute la journée',
      guidedTours: 'Visites Guidées',
      guidedToursDesc: 'Guides égyptologues professionnels pour toutes les visites de temples',
      pool: 'Piscine',
      poolDesc: 'Piscine sur le pont avec vue panoramique sur le Nil',
      entertainment: 'Divertissement',
      entertainmentDesc: 'Divertissements nocturnes incluant spectacles nubiens et soirées Galabeya',
      wifi: 'Accès Wi-Fi',
      wifiDesc: 'Restez connecté avec le service internet à bord',
      housekeeping: 'Ménage Quotidien',
      housekeepingDesc: 'Service de ménage premium deux fois par jour',
      personalService: 'Service Personnel',
      personalServiceDesc: 'Personnel attentif dédié à votre confort',
      safety: 'Sécurité',
      safetyDesc: 'Protocoles de sécurité 24h/24',
    },
    accommodations: {
      tagline: 'Hébergements',
      title: 'Cabines & Suites de Luxe',
      description: 'Chaque cabine à bord du Prince Omar a été conçue pour votre confort.',
      standardRoom: 'Cabine Standard',
      royalSuite: 'Suite Royale',
      roomsAvailable: 'Chambres Disponibles',
      suitesAvailable: 'Suites Disponibles',
      viewAll: 'Voir Tous les Hébergements',
      premiumExperience: 'Expérience Premium',
      inquireRoom: 'Se Renseigner sur Cette Chambre',
    },
    gallery: {
      tagline: 'Galerie',
      title: 'Découvrez la Beauté',
      description: 'Découvrez le monde de la croisière Prince Omar sur le Nil à travers notre galerie.',
      viewFull: 'Voir la Galerie Complète',
      all: 'Tout',
      exterior: 'Extérieur',
      interior: 'Intérieur',
      cabins: 'Cabines',
      dining: 'Restaurant',
      deck: 'Pont',
    },
    contact: {
      tagline: 'Contactez-Nous',
      title: 'Nous Contacter',
      description: 'Prêt pour votre aventure sur le Nil? Nous sommes là pour vous aider à planifier la croisière parfaite.',
      readyToSail: 'Prêt à Naviguer?',
      beginJourney: 'Commencez Votre Voyage sur le Nil Aujourd\'hui',
      ctaDescription: 'Contactez-nous pour réserver votre croisière inoubliable.',
      whatsappUs: 'WhatsApp',
      emailUs: 'Email',
      loveToHear: 'Nous Serions Ravis de Vous Entendre',
      helpText: 'Que vous ayez des questions sur nos croisières ou besoin d\'aide pour réserver, notre équipe est prête à vous aider.',
      whatsapp: 'WhatsApp',
      fastestResponse: 'Réponse la plus rapide • Cliquez pour discuter',
      phone: 'Téléphone',
      available7Days: 'Disponible 7 jours sur 7',
      email: 'Email',
      respondWithin: 'Nous répondons sous 24 heures',
      location: 'Emplacement',
      website: 'Site Web',
      sendMessage: 'Envoyer un Message',
      yourName: 'Votre Nom',
      enterName: 'Entrez votre nom',
      emailAddress: 'Adresse Email',
      phoneNumber: 'Numéro de Téléphone',
      yourMessage: 'Votre Message',
      tellUs: 'Parlez-nous de vos projets de voyage...',
      sendViaWhatsapp: 'Envoyer via WhatsApp',
      messageSentVia: 'Votre message sera envoyé via WhatsApp',
      nileRiver: 'Nil',
      luxorAswan: 'Louxor & Assouan, Égypte',
    },
    footer: {
      description: 'Vivez la beauté intemporelle du Nil à bord de notre croisière de luxe.',
      quickLinks: 'Liens Rapides',
      ourCruises: 'Nos Croisières',
      contactUs: 'Contact',
      allRights: 'Tous droits réservés.',
    },
    common: {
      respond24h: 'Nous répondons sous 24 heures • Disponible 7 jours sur 7',
    },
  },
  es: {
    nav: {
      home: 'Inicio',
      cruises: 'Nuestros Cruceros',
      accommodations: 'Alojamientos',
      gallery: 'Galería',
      contact: 'Contacto',
      bookNow: 'Reservar Ahora',
    },
    hero: {
      tagline: 'Experiencia de Crucero de Lujo por el Nilo',
      title: 'Príncipe',
      titleHighlight: 'Omar',
      description: 'Embárquese en un viaje por el antiguo Egipto a bordo de nuestro magnífico crucero de 5 estrellas. Descubra templos atemporales y paisajes impresionantes con un lujo incomparable.',
      bookJourney: 'Reserve Su Viaje',
      exploreCruises: 'Explorar Cruceros',
      luxuryRooms: 'Habitaciones de Lujo',
      royalSuites: 'Suites Reales',
      rating: 'Calificación',
    },
    cruises: {
      tagline: 'Nuestros Viajes',
      title: 'Itinerarios de Cruceros por el Nilo',
      description: 'Elija entre nuestras experiencias de crucero cuidadosamente seleccionadas, cada una ofreciendo perspectivas únicas de las maravillas antiguas de Egipto.',
      luxorToAswan: 'Luxor a Asuán',
      aswanToLuxor: 'Asuán a Luxor',
      nights: 'Noches',
      days: 'Días',
      everyMonday: 'Cada Lunes',
      everyFriday: 'Cada Viernes',
      highlights: 'Destacados',
      inquireNow: 'Consultar Ahora',
      bookThisCruise: 'Reservar Este Crucero',
      luxorDesc: 'Comience su viaje en Luxor, el museo al aire libre más grande del mundo, y navegue hacia el sur hasta la encantadora ciudad de Asuán.',
      aswanDesc: 'Comience en Asuán, navegue por las suaves aguas del Nilo y termine en la legendaria Luxor.',
      itinerary: 'Itinerario Día a Día',
    },
    included: {
      tagline: 'Comodidades',
      title: 'Qué Está Incluido',
      description: 'Cada detalle ha sido cuidadosamente considerado para que su viaje sea extraordinario.',
      fullBoard: 'Pensión Completa',
      fullBoardDesc: 'Exquisito desayuno, almuerzo y cena con cocina internacional y local',
      welcomeDrink: 'Bebida de Bienvenida',
      welcomeDrinkDesc: 'Cóctel de bienvenida refrescante al embarcar',
      teaCoffee: 'Té y Café',
      teaCoffeeDesc: 'Té y café gratuitos disponibles todo el día',
      guidedTours: 'Visitas Guiadas',
      guidedToursDesc: 'Guías egiptólogos profesionales para todas las visitas a templos',
      pool: 'Piscina',
      poolDesc: 'Piscina en cubierta con vistas panorámicas al Nilo',
      entertainment: 'Entretenimiento',
      entertainmentDesc: 'Entretenimiento nocturno con espectáculos nubios y fiestas Galabeya',
      wifi: 'Acceso Wi-Fi',
      wifiDesc: 'Manténgase conectado con el servicio de internet a bordo',
      housekeeping: 'Limpieza Diaria',
      housekeepingDesc: 'Servicio de limpieza premium dos veces al día',
      personalService: 'Servicio Personal',
      personalServiceDesc: 'Personal atento dedicado a su comodidad',
      safety: 'Seguridad',
      safetyDesc: 'Protocolos de seguridad las 24 horas',
    },
    accommodations: {
      tagline: 'Alojamientos',
      title: 'Cabinas y Suites de Lujo',
      description: 'Cada cabina a bordo del Príncipe Omar ha sido diseñada pensando en su comodidad.',
      standardRoom: 'Cabina Estándar',
      royalSuite: 'Suite Real',
      roomsAvailable: 'Habitaciones Disponibles',
      suitesAvailable: 'Suites Disponibles',
      viewAll: 'Ver Todos los Alojamientos',
      premiumExperience: 'Experiencia Premium',
      inquireRoom: 'Consultar Sobre Esta Habitación',
    },
    gallery: {
      tagline: 'Galería',
      title: 'Experimente la Belleza',
      description: 'Eche un vistazo al mundo del crucero Príncipe Omar por el Nilo a través de nuestra galería.',
      viewFull: 'Ver Galería Completa',
      all: 'Todo',
      exterior: 'Exterior',
      interior: 'Interior',
      cabins: 'Cabinas',
      dining: 'Restaurante',
      deck: 'Cubierta',
    },
    contact: {
      tagline: 'Contáctenos',
      title: 'Contacto',
      description: '¿Listo para su aventura por el Nilo? Estamos aquí para ayudarle a planificar el crucero perfecto.',
      readyToSail: '¿Listo para Navegar?',
      beginJourney: 'Comience Su Viaje por el Nilo Hoy',
      ctaDescription: 'Contáctenos para reservar su crucero inolvidable.',
      whatsappUs: 'WhatsApp',
      emailUs: 'Email',
      loveToHear: 'Nos Encantaría Saber de Usted',
      helpText: 'Ya sea que tenga preguntas sobre nuestros cruceros o necesite ayuda con la reserva, nuestro equipo está listo para ayudarle.',
      whatsapp: 'WhatsApp',
      fastestResponse: 'Respuesta más rápida • Clic para chatear',
      phone: 'Teléfono',
      available7Days: 'Disponible 7 días a la semana',
      email: 'Email',
      respondWithin: 'Respondemos en 24 horas',
      location: 'Ubicación',
      website: 'Sitio Web',
      sendMessage: 'Enviar Mensaje',
      yourName: 'Su Nombre',
      enterName: 'Ingrese su nombre',
      emailAddress: 'Correo Electrónico',
      phoneNumber: 'Número de Teléfono',
      yourMessage: 'Su Mensaje',
      tellUs: 'Cuéntenos sobre sus planes de viaje...',
      sendViaWhatsapp: 'Enviar vía WhatsApp',
      messageSentVia: 'Su mensaje se enviará vía WhatsApp',
      nileRiver: 'Río Nilo',
      luxorAswan: 'Luxor y Asuán, Egipto',
    },
    footer: {
      description: 'Experimente la belleza atemporal del Nilo a bordo de nuestro crucero de lujo.',
      quickLinks: 'Enlaces Rápidos',
      ourCruises: 'Nuestros Cruceros',
      contactUs: 'Contacto',
      allRights: 'Todos los derechos reservados.',
    },
    common: {
      respond24h: 'Respondemos en 24 horas • Disponible 7 días a la semana',
    },
  },
};
